// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lekcoboupqohmlowoeor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxla2NvYm91cHFvaG1sb3dvZW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTU1ODEsImV4cCI6MjA1OTg5MTU4MX0.BWLrz909MaNVwbxzNgCvd0E81o52EwzA2cAGYaqZp_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);